### ISSUE TITLE
Random order in Lua > 5.1

### ISSUE THREAD

**Issue by yuppox** [jonathanpoelen/lua-xmlparser#1]
Using Lua 5.1, the order of things in the table is consistent.

In Lua 5.2+, it seems to be random. Tags/elements are in the same order but attributes are not.

How can I fix this?

**Comment by jonathanpoelen** [comment]
The order in which the indices are enumerated with `pairs` or `next  is not specified:

- 5.1: https://www.lua.org/manual/5.2/manual.html#pdf-next
- 5.2: https://www.lua.org/manual/5.1/manual.html#pdf-next

The difference is that Lua 5.2.1 introduced randomization of seeds for hashing.

I will add an `orderedattrs` field which will be a table on name / value pairs.
